openapi: 3.0.1

info:
  title: Coinbase Exchange Public API
  version: 1.0.0
  description: Public API for accessing data from Coinbase Exchange

servers:
  - url: https://api.exchange.coinbase.com
    description: Coinbase Exchange main API

paths:
  /products/{product_id}/stats:
    get:
      tags:
        - ApiCoinStats
      summary: Get select coin-pair statistics
      description: Retrieves 30day and 24hour stats including last known price for a selected coin-pair as described on https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_getproductstats
      operationId: getCoinStats
      parameters:
        - name: product_id
          in: path
          description: Product identifier, e.g. BTC-USD
          required: true
          schema:
            type: string
          example: BTC-USD
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinStats'
        '400':
          description: Bad request. Invalid product_id.
        '500':
          description: Unexpected error

components:
  schemas:
    CoinStats:
      type: object
      properties:
        open:
          type: string
          description: Open price for coin-pair in current trading day
          example: "89907.44"
        high:
          type: string
          description: Highest price for coin-pair in current trading day
          example: "92907.44"
        low:
          type: string
          description: Lowest price for coin-pair in current trading day
          example: "87907.44"
        last:
          type: string
          description: Last known price for coin-pair
          example: "91907.44"
        volume:
          type: string
          description: 24-hour volume in selected currency (e.g. amount of BTC traded in last 24 hours)
          example: "10710.55244289"
        volume_30day:
          type: string
          description: 30-day volume in selected currency (e.g. amount of BTC traded in last 30 days)
          example: "285985.01131518"
      required:
        - open
        - high
        - low
        - last
        - volume
        - volume_30day