openapi: 3.0.1

info:
  title: Coinbase Public API
  version: 1.0.0
  description: Public API for accessing data from Coinbase

servers:
  - url: https://api.coinbase.com
    description: Coinbase main API

paths:
  /api/v3/brokerage/market/products:
    get:
      tags:
        - ApiCoinPair
      summary: Get list of coins
      description: Retrieves list of coins with detailed trading information as described on https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_getproducts
      operationId: getListOfCoinsWithTradingDetails
      parameters:
        - name: limit
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 250
        - name: offset
          in: query
          description: Pagination offset
          required: false
          schema:
            type: integer
            minimum: 0
        - name: product_type
          in: query
          description: Filter by product type
          required: false
          schema:
            type: string
            enum: [SPOT, FUTURE]
          example: SPOT
        - name: product_ids
          in: query
          description: Comma-separated list of product IDs
          required: false
          schema:
            type: array
            items:
              type: string
          example: BTC-USD, BTC-EUR
        - name: products_sort_order
          in: query
          description: Sort order for results
          required: false
          schema:
            type: string
            enum: [PRODUCTS_SORT_ORDER_UNDEFINED, PRODUCTS_SORT_ORDER_VOLUME_24H_DESCENDING, PRODUCTS_SORT_ORDER_LIST_TIME_DESCENDING]
          example: PRODUCTS_SORT_ORDER_VOLUME_24H_DESCENDING
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/CoinPair'
                  num_products:
                    type: integer
        '500':
          description: Unexpected error

components:
  schemas:
    CoinPair:
      type: object
      properties:
        product_id:
          type: string
          description: Unique identifier for the product pair
          example: "BTC-USD"
        base_currency_id:
          type: string
          description: Unique identifier for the base currency
          example: "BTC"
        quote_currency_id:
          type: string
          description: Unique identifier for the quote currency
          example: "USD"
        base_display_symbol:
          type: string
          description: Display symbol for base currency
          example: "BTC"
        quote_display_symbol:
          type: string
          description: Display symbol for quote currency
          example: "USD"
        base_name:
          type: string
          description: Display name of the base currency
          example: "Bitcoin"
        quote_name:
          type: string
          description: Display name of the quote currency
          example: "US Dollar"
        price:
          type: string
          description: Current price of the product pair
          example: "88828.96"
        price_percentage_change_24h:
          type: string
          description: 24-hour price percentage change
          example: "1.97654041425943"
        volume_24h:
          type: string
          description: 24-hour trading volume in base currency
          example: "11537.70988692"
        approximate_quote_24h_volume:
          type: string
          description: Approximate quote currency volume (i.e. base currency volume * quote currency price) in USD/EUR/...
          example: "1024882770.04"
        volume_percentage_change_24h:
          type: string
          description: 24-hour volume percentage change
          example: "143.92418656128531"
        is_disabled:
          type: boolean
          description: Indicates if trading is disabled
          example: false
        new:
          type: boolean
          description: Indicates if the product is newly listed
          example: false
        status:
          type: string
          description: Current status of the product
          example: "online"
        product_type:
          type: string
          description: Type of product (e.g. SPOT)
          example: "SPOT"
      required:
        - product_id
        - base_currency_id
        - quote_currency_id
        - price
        - price_percentage_change_24h
        - volume_24h
        - volume_percentage_change_24h

