openapi: 3.0.1
info:
  title: CoinChange Backend API
  version: 1.0.0
  description: API definition for the CoinChange application.

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Authorization header using the Bearer scheme.
  schemas:
    ErrorDto:
      type: object
      properties:
        errorStatusValue:
          type: integer
          format: int32
          example: 404
        errorStatus:
          type: string
          example: BAD_REQUEST
        errorTime:
          type: string
          format: date-time
          example: "2018-08-29T23:20:50"
        errorMessage:
          type: string
          example: User with same username/email and with active account already exists
        errorBusinessCode:
          type: string
          example: USER_ALREADY_EXISTS
      required:
        - errorStatusValue
        - errorStatus
        - errorTime
    UserRegistrationRequestDto:
      type: object
      properties:
        username:
          type: string
          example: JohnDow
        email:
          type: string
          example: JohnDow@gmail.com
        password:
          type: string
          example: JohnDowPassw
      required:
        - username
        - email
        - password
    UserLoginRequestDto:
      type: object
      properties:
        usernameOrEmail:
          type: string
          example: JohnDow
        password:
          type: string
          example: JohnDowPassw
      required:
        - usernameOrEmail
        - password
    RoleDto:
      type: object
      properties:
        roleName:
          type: string
          description: Name of the role.
          example: ADMIN
          required:
            - type
        operations:
          type: array
          description: List of operations associated with the role.
          items:
            type: string
            description: Name of the operation.
            example: ACCESS_ADMIN_SECTION
            required:
              - type
      required:
        - roleName
        - operations
    UserLoginResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: JohnDow
        email:
          type: string
          example: JohnDow@gmail.com
        createdAt:
          type: string
          format: date-time
          example: "2018-08-29T23:20:50"
        updatedAt:
          type: string
          format: date-time
          example: "2018-08-29T23:20:50"
        validTo:
          type: string
          format: date-time
          example: "2100-01-01T00:00:00"
        jwtToken:
          type: string
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
        roles:
          type: array
          description: List of roles and their associated operations.
          items:
            $ref: '#/components/schemas/RoleDto'
      required:
        - id
        - username
        - email
        - createdAt
        - updatedAt
        - validTo
        - jwtToken
        - roles
    RefreshTokenResponseDto:
      type: object
      properties:
        jwtToken:
          type: string
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
      required:
        - jwtToken


    PortfolioResponseDto:
      type: object
      properties:
        currenciesBalances:
          type: array
          items:
            $ref: '#/components/schemas/UserCurrencyBalanceResponseDto'
      required:
        - currenciesBalances
    CurrencyResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        code:
          type: string
          example: USD
        name:
          type: string
          example: Dollar
        isActive:
          type: boolean
          example: true
        type:
          type: string
          example: F - fiat, C - crypto
      required:
        - id
        - code
        - name
        - isActive
        - type
    UserCurrencyBalanceResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        currency:
          $ref: '#/components/schemas/CurrencyResponseDto'
        balance:
          type: number
          example: 1000
        updatedAt:
          type: string
          format: date-time
          example: "2018-08-29T23:20:50"
      required:
        - id
        - currency
        - balance
        - updatedAt
    CurencyConversionRateResponseDto:
      type: object
      properties:
        soldCurrencyId:
          type: integer
          format: int64
          example: 1
        soldCurrencyCode:
          type: string
          example: EUR
        boughtCurrencyId:
          type: integer
          format: int64
          example: 1
        boughtCurrencyCode:
          type: string
          example: USD
        conversionRate:
          type: number
          example: 1000
      required:
        - soldCurrencyId
        - soldCurrencyCode
        - boughtCurrencyId
        - boughtCurrencyCode
        - conversionRate

paths:
  /user/login:
    post:
      tags:
        - ApiUser
      summary: Login user
      operationId: loginUser
      description: |
        Login a user
      requestBody:
        description: login attributes provided by a user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequestDto'
        required: true
      responses:
        201:
          description: User login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
  /user/register:
    post:
      tags:
        - ApiUser
      summary: Register a new user
      operationId: createUser
      description: |
        Register a new user
      requestBody:
        description: registration attributes provided by new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequestDto'
        required: true
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
  /user/refresh-token:
    post:
      tags:
        - ApiUser
      summary: Refresh JWT token
      operationId: refreshToken
      description: |
        Refresh the JWT token using a valid existing token.
      security:
        - bearerAuth: []
      responses:
        201:
          description: New JWT token generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponseDto'
        401:
          description: Unauthorized - JWT token is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
        400:
          description: Bad Request - Invalid parameters or missing required fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'



  /portfolio:
    get:
      tags:
        - ApiPortfolio
      summary: Get user´s portfolio
      operationId: getPortfolio
      description: |
        Returns portfolio of the client with information about his fiat and crypto currencies
      security:
        - bearerAuth: [ ]
      responses:
        201:
          description: Whole portfolio of the user (balances of all user's fiat and crypto currencies)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
  /currencies:
    get:
      tags:
        - ApiCurrencies
      summary: Get all currently supported currencies
      operationId: getSupportedCurrencies
      description: |
        Returns all currently supported currencies
      security:
        - bearerAuth: [ ]
      responses:
        201:
          description: List of all currently supported currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
  /currencies/{type}:
    get:
      tags:
        - ApiCurrencies
      summary: Get all currently supported currencies for selected type
      operationId: getSupportedCurrenciesForType
      parameters:
        - name: type
          in: path
          description: Currency type identifier, e.g. F - fiat, C - crypto
          required: true
          schema:
            type: string
          example: F - fiat, C - crypto
      description: |
        Returns all currently supported currencies for selected type
      security:
        - bearerAuth: [ ]
      responses:
        201:
          description: List of all currently supported currencies for selected type
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'

  /currencies/conversion-rate/{soldCurrencyCode}-{boughtCurrencyCode}:
    get:
      tags:
        - ApiCurrencyConversionRate
      summary: Get conversion rate for pair of currencies
      operationId: getConversionRate
      parameters:
        - name: soldCurrencyCode
          in: path
          description: Currency code of sold currency
          required: true
          schema:
            type: string
          example: EUR
        - name: boughtCurrencyCode
          in: path
          description: Currency code of bought currency
          required: true
          schema:
            type: string
          example: USD
      description: |
        Returns conversion rate for provided pair of currencies
      security:
        - bearerAuth: [ ]
      responses:
        201:
          description: Conversion rate for provided pair of currencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurencyConversionRateResponseDto'
        400:
          description: Variants of Bad request - returned ErrorDto will specify particular type of thrown error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'